## Step 1: 
### This imports the NumPy library as np to use it in the code.

In [5]:
import numpy as np

## Step 2: 
### This Creates a 2D array of shape (4, 4) filled with values 1-16 and print its shape and dtype.

In [53]:
            #Columns 0  1  2  3       # Rows
array2d = np.array([[1, 2, 3, 4],     # 0
                    [5, 6, 7, 8],     # 1
                    [9, 10, 11, 12],  # 2
                    [13, 14, 15, 16]])# 3

print(array2d.shape)
array2d.dtype

(4, 4)


dtype('int64')

## Step 3: 
### This uses slicing to extract the second column and the last row

In [77]:
# all rows, column 1 (Second column)
print(array2d[:, 1]) 

# row 3, all columns (Last row)
print(array2d[3, :]) 


[ 2  6 10 14]
[13 14 15 16]


## Step 4: 
### Use a boolean mask to select all values greater than the array's mean.

In [69]:
mask = (array2d > array2d.mean())
print(array2d)
print("The mean of the array is:", array2d.mean() , "\n")
print("All values greater than the array's mean:")
print(array2d[mask])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
The mean of the array is: 8.5 

All values greater than the array's mean:
[ 9 10 11 12 13 14 15 16]


## Step 5: 
### Add a 1D row array to every row of a 2D array using broadcasting, and verify the result manually.

In [59]:
array1d = np.array([1, 2, 3, 4])

result = array2d + array1d

print(array2d)
print("+")
print(array1d)
print("=")
print(result)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
+
[1 2 3 4]
=
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]]
